### ISSUE TITLE
Bookmarks incomplete (Backup/Restore function) Feature request(s)

### ISSUE THREAD

**Issue by happykeppi** [thecoder75/liveme-pro-tools#18] opened 2018-03-21 13:12 UTC
I was wondering if you can ensure that the backup and restore function is working properly. I made a backup the other day and restored it on another computer just to notice that the bookmarks remained the same. After taking a look into the tar file, I figured the last modification date of three out of the four files was almost one day ago although I used the client on the same day (added bookmarks, downloaded and watched stuff etc.). Here's the data in total:

tar file (March 20, 2018 - 4:37 PM)
- downloaded.json (March 19, 2018 - 9:46 PM)
- watched.json (March 19, 2018 - 9:46 PM)
- profiles.json (March 20, 2018 - 8:12 AM)
- bookmarks.jon (March 19, 2018 - 9:46 PM)

On the other hand, I can't tell for sure, but I think the latest changes were missing as well after I closed the client and used it again on the following day. What could be the reason for the files not being updated properly?

Besides, I would like to ask if it would be possible to add a few additional filters (just like country and available replays (>1)) to the general search function as well as to make the comments and likes for the replays visible on demand like it is in the official app. Would it be also a good idea to add a sticky feature, so you can pin certain profile on the top of your bookmarks, so you don't need to search for them in the list? Could you imagine adding a sort function (by name as well as latest broadcast date for example) for the bookmarks? Finally, I would appreciate if there's an option to manually deactivate the auto-pruning setting for profiles that have been inactive for more than 30 days. Thanks for your efforts and support as well as the great app!

**Comment by happykeppi** [comment] 2018-03-21 13:23
**Update**
I just performed another backup after adding a profile. The bookmarks.json (and the other two files) has still the same date as above while the profiles.json has a date from March 21. So the backup is not working, at least for me.

**Comment by thecoder75** [comment] 2018-03-22 00:19
1.  The backup and restore has been tested successfully on several Linux systems by me and this is the first report of any issue regarding this that I've received.  Unfortunately since this is the near the end of the development cycle on this project by me, this issue will not be addressed by myself at this time.  If someone would like to diagnose and submit a pull request with any updates or fixes on this issue I'll be happy to review and merge them into the project.

2.  I'm sorry, but the general search function is only meant to be general without any filters.

3.  This app is not meant to be like the official app in regards to how the comments and likes work.  It is for people who want to search, view and download replays and track accounts.

4.  Changing how the bookmarks window lists entries and such is not something I'm focusing on at this time.

5.  The reason for the auto-pruning being limited to 3 days is to avoid data issues when the profile history list gets to be over 10K entries as data corruption occurs causing the list to get wiped completely out.  

**Just so you know, I'm only performing some minor bug fixes on this project now.  I'm planning on moving it over to an actual desktop application so I can gain more powerful support and manageability that I cannot get in Electron/NodeJS anymore along without all the bugs and issues I've been discovering.**

**Comment by thecoder75** [comment] 2018-04-09 12:44
Closing issue as I cannot reproduce original issue.

**Closed by thecoder75** 2018-04-09 12:44 UTC
Labels: bug, feature, question
